[package]
name = "rts-rs"
version = "0.1.0"
edition = "2021"
default-run = "play"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

ggez = "0.7.0"
rand = "0.8.5"